version: '3.9'

services:
  server:
    build: .
    ports: 
      - '5000:5000'
    volumes:
      - ./:/app/
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: 
